unstable_features = true #Unstable

binop_separator = "Back"

blank_lines_upper_bound = 2
brace_style = "PreferSameLine"

wrap_comments = true #Unstable
comment_width = 100 #Unstable

edition = "2021"
enum_discrim_align_threshold = 25 #Unstable

format_code_in_doc_comments = true #Unstable

format_string = true #Unstable

indent_stye = "Visual" #Unstable

match_block_trailing_comma = true #Unstable

imports_granularity = "Module" #Unstable

newline_style = "Unix"

overflow_delimited_expr = true #Unstable

group_imports = "StdExternalCrate" #Unstable